# Generated by Django 5.1.2 on 2024-10-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.IntegerField()),
                ('academic_score', models.FloatField()),
                ('consistency_score', models.FloatField()),
                ('core_engineering_score', models.FloatField()),
                ('hackathon_participation', models.IntegerField()),
                ('paper_presentations', models.IntegerField()),
                ('teacher_assistance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.student')),
            ],
        ),
    ]
